<?php
/** @var \Midnight\UserModule\Entity\User[] $users */
$users = $this->users;
?>
<h1>Benutzer</h1>
<div class="page-content">
    <ul class="page-options">
        <li><a href="<?= $this->url('zfcadmin/user/create') ?>">Benutzer erstellen&hellip;</a></li>
    </ul>
    <table>
        <thead>
        <tr>
            <th>E-Mail</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($users as $user): ?>
            <?php
            $view_url = $this->url('zfcadmin/user/user', array('user_id' => $user->getId()));
            ?>
            <tr>
                <td><a href="<?= $view_url ?>"><?= $user->getEmail() ?></a></td>
            </tr>
        <?php endforeach ?>
        </tbody>
    </table>
</div>
