<?php
/** @var \Midnight\UserModule\Entity\User $user */
$user = $this->user;
?>
<h1><?= $user->getLabel() ?></h1>
<ul class="page-nav">
    <li class="back"><a href="<?= $this->url('zfcadmin/user') ?>">Alle Benutzer</a></li>
    <li><a href="<?= $this->url('zfcadmin/user') ?>"><?= $user->getLabel() ?></a></li>
    <li class="current">
        <a href="<?= $this->url('zfcadmin/user/user/set_password', array('user_id' => $user->getId())) ?>">
            Passwort
        </a>
    </li>
</ul>
<div class="page-content">
    <?= $this->form($this->form) ?>
</div>
