<?php
/** @var \Midnight\User\Entity\User $user */
$user = $this->user;
?>
<h1><?= $user->getLabel() ?></h1>
<ul class="page-nav">
    <li class="back"><a href="<?= $this->url('zfcadmin/user') ?>">Alle Benutzer</a></li>
    <li class="current"><a href="<?= $this->url('zfcadmin/user') ?>"><?= $user->getLabel() ?></a></li>
</ul>
<div class="page-content">
    <dl>
        <dt>E-Mail</dt>
        <dd><?= $user->getEmail() ?></dd>
    </dl>
</div>